# Generated by Django 5.2.7 on 2025-10-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='bg/banner.png', upload_to='banner', verbose_name='轮播图')),
                ('order', models.IntegerField(default=0, verbose_name='轮播图排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '轮播图表',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='公告标题')),
                ('content', models.TextField(default='', verbose_name='公告内容')),
                ('img', models.ImageField(default='bg/notice.png', upload_to='notice', verbose_name='公告图片')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎表'},
        ),
    ]
