# Generated by Django 5.2.7 on 2025-10-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0002_banner_notice_alter_welcome_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='order',
            field=models.IntegerField(default=0, verbose_name='公告排序'),
        ),
    ]
