# Generated by Django 5.2.7 on 2025-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0003_notice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='bg/bottom.png', upload_to='bottom', verbose_name='底部图片')),
                ('order', models.IntegerField(default=0, verbose_name='底部排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '底部表',
            },
        ),
    ]
