# Generated by Django 5.2.7 on 2025-10-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0004_bottom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='区域名称')),
                ('desc', models.TextField(default='', verbose_name='区域简称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '区域表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='用户姓名')),
                ('avatar', models.ImageField(default='default.png', upload_to='user', verbose_name='用户头像')),
                ('score', models.IntegerField(default=0, verbose_name='用户积分')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='采集人姓名')),
                ('name_pingyin', models.CharField(default='', max_length=255, null=True, verbose_name='采集人姓名拼音')),
                ('avatar', models.ImageField(default='default.png', upload_to='collecton/%Y/%m/%d/', verbose_name='采集人头像')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community_service.area', verbose_name='风格区域')),
            ],
            options={
                'verbose_name_plural': '采集表',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community_service.userinfo', verbose_name='负责用户'),
        ),
    ]
