# Generated by Django 5.2.7 on 2025-10-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_service', '0005_area_userinfo_collection_area_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collecton',
        ),
    ]
